features:
  - key: call_newapi_getUserById
    enabled: true // enabled为true时，rule才生效
    rule: {893,342,1020-1120,%30} // 按照用户ID来做灰度
  - key: call_newapi_registerUser
    enabled: true
    rule: {1391198723, %10}  //按照手机号来做灰度
  - key: newalgo_loan
    enabled: true
    rule: {0-1000} //按照贷款(loan)的金额来做灰度